name: security-scans
on:
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run OPA policy tests
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
    
      - name: Execute tests (skip if dirs absent)
        run: |
          set -e
          for dir in modules/org/tests modules/network/tests; do
            if [ -d "$dir" ]; then
              echo "Running OPA tests in $dir"
              opa test "$dir"
            else
              echo "Skipping $dir (directory not found)"
            fi
          done

